<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blaulichtspotter Solingen</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 0; background-color: #f4f4f4; }
        header { background: #ff0000; color: white; padding: 15px; text-align: center; font-size: 24px; }
        .container { width: 80%; margin: auto; overflow: hidden; }
        .gallery { display: flex; flex-wrap: wrap; justify-content: space-around; }
        .gallery img { width: 30%; margin: 10px; border-radius: 10px; }
        footer { background: #222; color: white; text-align: center; padding: 10px; margin-top: 20px; }
    </style>
</head>
<body>
    <header>
        Blaulichtspotter Solingen
    </header>
    <div class="container">
        <h2>Aktuelle Einsätze</h2>
        <p>Hier findest du Bilder und Informationen zu aktuellen Unfällen und Einsätzen in Solingen.</p>
        <div class="gallery">
            <img src="unfall1.jpg" alt="Unfall auf der Autobahn">
            <img src="brand1.jpg" alt="Feuerwehreinsatz in der Innenstadt">
            <img src="rtw1.jpg" alt="Rettungswagen im Einsatz">
        </div>
    </div>
    <footer>
        &copy; 2025 Blaulichtspotter Solingen - Yannick Bender
    </footer>
</body>
</html>

